### Feedback Tour Average Rating API Test

# Lấy thông tin trung bình rating của Tour
GET {{baseUrl}}/api/Feedback/tour/1/average-rating
Content-Type: application/json

###

# Lấy thông tin trung bình rating của Tour khác
GET {{baseUrl}}/api/Feedback/tour/2/average-rating
Content-Type: application/json

###

# Test với Tour không tồn tại
GET {{baseUrl}}/api/Feedback/tour/999/average-rating
Content-Type: application/json

###

# Test với Tour không có rating
GET {{baseUrl}}/api/Feedback/tour/3/average-rating
Content-Type: application/json
